[package]
name = "blve_dev_server"
version = "0.0.1"
edition = "2021"

[dependencies]
lunas_compiler = { version = "0.1.0", path = "../lunas_compiler", features = [
  "playground",
] }
serde_json = "1.0.120"
tokio = { version = "1", features = ["full"] }
warp = "0.3"

[features]
playground = []
